services:
  progressacademy-webapi:
    build:
      context: .
      dockerfile: ProgressAcademy.WebApi/Dockerfile
    ports:
      - "7104:80"
    depends_on:
      - mongo
    environment:
      - MONGO_DB_CONNECTION_STRING=mongodb://admin:123qwe@mongo:27017/ProgressAcademy
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=123qwe
      - MONGO_INITDB_DATABASE=ProgressAcademy
    networks:
      - my-network

  mongo:
    image: mongo:4.4
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 123qwe
      MONGO_INITDB_DATABASE: ProgressAcademy
    ports:
      - "27018:27018"
    volumes:
      - mongo-data:/data/db
      - ./ProgressAcademy.Data/scripts:/docker-entrypoint-initdb.d/
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
