version: '3.8'

services:
  mongo:
    image: mongo:4.4 
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    restart: always
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: mongo
      DB_ADDR: mongo
      DB_PORT: 27017
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_IMPORT: /tmp/realm-export.json
    volumes:
      - ./keycloak-data:/opt/jboss/keycloak/standalone/data
    ports:
      - "8080:8080" 
    depends_on:
      mongo:
        condition: service_healthy 

volumes:
  mongo-data:
    driver: local
